### ISSUE TITLE
About the usage of _NL+ for composite types

### ISSUE THREAD

**Issue by Jenselme** [geographika/mappyfile#11]
I encountered parsing issue with this project (which is really nice BTW). After doing some digging, it was caused by:
```
  PROJECTION "init=epsg:2056"
  END
```

I was able to correct the problem by replacing this block by:
```
  PROJECTION
    "init=epsg:2056"
  END
```

But the map file is parsed correctly by `shp2img` and by `mapserv`. I did some tests with `CLASS NAME "Graticule"`, `LABEL COLOR 0 0 0`, `GRID LABELFORMAT '%.0f'` and `PROJECTION "init=epsg:4326" END` and the map files is parsed without any problem.

So I guess the grammar definition should use `_NL*` instead of `_NL+`. What do you think? I can do a PR for this if you want.

**Comment by geographika** [comment]
@Jenselme - thanks for raising this. I will look into it further to see if ``_NL*`` could cause issues elsewhere.

**Comment by Jenselme** [comment]
OK, keep me posted.

**Comment by geographika** [comment]
@Jenselme - should be fixed on master now.

**Comment by Jenselme** [comment]
That solved it. Thanks.
