### ISSUE TITLE
Style OFFSET: mixed attribute and numerical value fail to parse

### ISSUE THREAD

**Issue by luziancaduff** [geographika/mappyfile#114]
When a Style is defined with an offset with one value defined as attribute and one as numerical value (ex. `OFFSET [attribute] 5`, mappyfile fails to parse the file. The parser fails whenever one value is defined as attribute and the other as numeric value. The [documentation for the style element](https://mapserver.org/mapfile/style.html) says, that it should be possible and the map is also rendered correctly by mapfile. 
The error occured trying to parse a style defined for a line with an y-OFFSET of -999, what renders the outline of a thick line. 
The following example shows a mapfile, which causes the parsing error. 

```
MAP
    NAME "sample"
    STATUS ON
    SIZE 600 400
    EXTENT -180 -90 180 90
    LAYER
        CLASS
            NAME "test"
            TYPE     LINE
            STYLE
                WIDTH 1.6
                COLOR 245 0 255
                OFFSET [attribute] -999
            END
        END
    END
END
```

**Comment by geographika** [comment]
@luziancaduff - thanks for reporting this. The referenced pull request should now allow this to be parsed correctly. There will hopefully be a new release over the next 2 weeks.
