### ISSUE TITLE
LABEL -> FONT and LABEL->POSITION gives errors in validate when attributes are used

### ISSUE THREAD

**Issue by LarsSchy** [geographika/mappyfile#118]
I have a mapfile with LABEL - FONT and LABEL - POSITION as attributes.
These gives errors when I run mappyfile validate on the mapfile.
I have made an example with some real data that I am using.
I managed to patch the schema for the font case. But was not successful with the position case. 
Mapserver version 7.2.2 on debian. Mappyfile version: 0.9.1

I have made a full example with everything except the font files here:
https://gist.github.com/LarsSchy/27916c896d35a524a123b69e4dbdcb54

The script above creates data in a geojson file with two features.

My result image looks like this when I run shp2img:

![text_test2](https://user-images.githubusercontent.com/17429588/106190459-fbfd9780-61a9-11eb-8af8-f867a3ff3533.png)

**Comment by geographika** [comment]
Hi @LarsSchy!

Thanks for reporting this. The validation didn't allow for attributes in LABEL POSITION, and there was a clash in LABEL FONT in the JSON rules. Both should be fixed in master now. 

You should be able to test with master using:

```
pip install git+git://github.com/geographika/mappyfile@master -U
```

**Comment by LarsSchy** [comment]
Many thanks Seth for the very quick response and fix.  It works perfect now!
