### ISSUE TITLE
Expression list element with apostrophe throws error.

### ISSUE THREAD

**Issue by b4l** [geographika/mappyfile#120]
`EXPRESSION {bla,d'apostrophe}` fails to parse even though mapserver handles this well.

**Comment by geographika** [comment]
Thanks for the report. This might be tricky..

**Comment by b4l** [comment]
Adding comma and apostrophe here https://github.com/geographika/mappyfile/blob/249b776b6071fa05b7b7f9179e5595452687e32f/mappyfile/mapfile.lalr.g#L155 might do the trick.

**Comment by geographika** [comment]
@b4l - thanks that suggestion worked. The example you posted should now be handled in master. You can test with:

```
pip install git+git://github.com/geographika/mappyfile@master -U
```

**Comment by b4l** [comment]
Thanks @geographika , seems to work fine. Actually identifying the list and split by `,` respectively a wildcard regex `.*` would probably be sufficient.
