### ISSUE TITLE
better pipy packaging : offer a source, and add license file

### ISSUE THREAD

**Issue by tigerfoot** [geographika/mappyfile#13]
On pypi only the whl is present.
Offering a source package would be a must (including tests).

Also whl is missing license file.

On the same side, having the release set in correlation here in github help to grab patches if needed.

**Comment by geographika** [comment]
@tigerfoot - thanks for those details.

https://pypi.python.org/pypi/mappyfile/#downloads now has the source package with docs and tests. 
The .whl also contains the license file. 

Could you explain further about the Github/release comment?

**Comment by tigerfoot** [comment]
@geographika for the release tag, the idea is the following.
You determine a commit being the release X.X.X (this one is used to create the X.X.X version you publish on pypi, and you tagged it the same here in github.
Is it more clear ? Do you need some examples ?

**Comment by geographika** [comment]
@tigerfoot - thanks that makes sense. I created a release which also adds a tag for v0.2.1

**Comment by geographika** [comment]
Hopefully the release tags help with the packaging (I presume it is for OpenSUSE? https://build.opensuse.org/package/show/devel:languages:python/python-mappyfile). Please reopen if I misunderstood the request.
