### ISSUE TITLE
Read symbolset files

### ISSUE THREAD

**Issue by Python-Ninja-Hebi** [geographika/mappyfile#135]
Hallo,

is it possible to include symbolset files like other include files, when reading mapserver files?

Is there a way to read symbolset files?

thanks

best regards Hebi

**Comment by geographika** [comment]
@Python-Ninja-Hebi - you can read symbol files using the following approach:

```python
from mappyfile.pprint import PrettyPrinter

import mappyfile
fn = r"symbols/symbols.sym"
mf = mappyfile.open(fn)
pp = PrettyPrinter()
print(pp.pprint(mf))
```
