### ISSUE TITLE
tests (python3)

### ISSUE THREAD

**Issue by tigerfoot** [geographika/mappyfile#14]
During packaging there's an issue with running test

```
[   20s] + /usr/bin/python3 setup.py test
[   20s] running test
[   20s] running egg_info
[   20s] writing mappyfile.egg-info/PKG-INFO
[   20s] writing dependency_links to mappyfile.egg-info/dependency_links.txt
[   20s] writing requirements to mappyfile.egg-info/requires.txt
[   20s] writing top-level names to mappyfile.egg-info/top_level.txt
[   20s] reading manifest file 'mappyfile.egg-info/SOURCES.txt'
[   20s] reading manifest template 'MANIFEST.in'
[   20s] writing manifest file 'mappyfile.egg-info/SOURCES.txt'
[   20s] running build_ext
[   20s] error: [Errno 2] No such file or directory: 'C:\\VirtualEnvs\\pmsmapserverdev\\Scripts\\activate_this.py'
[   20s] error: Bad exit status from /var/tmp/rpm-tmp.5rKNSp (%check)
```

For evident reason there's no C:\ drive under linux hosts ;-)
Also downloading something is strictly forbidden during build (happen in one shot vm with no external network access).
As packager I can grab myself before build  a tar.gz containing alll .map from mapserver.org, and inject it at the right place for running the tests.

**Comment by geographika** [comment]
@tigerfoot - that file was a remnant from downloading the initial test MAP files. I didn't think it would run as the file wasn't prefixed with test_ (as with the old Python 2 testing approach). 

In any case the file shouldn't be in that folder and has been removed.
