### ISSUE TITLE
Invalid value in COMPOSITE - 'compfilter'

### ISSUE THREAD

**Issue by LarsSchy** [geographika/mappyfile#144]
COMPFILTER is missing in the COMPOSITE block

mappyfile validate layer_comp.map 
layer_comp.map (Line: 124 Column: 3) ERROR: Invalid value in COMPOSITE - 'compfilter' does not match any of the regexes: '^__[a-z]+__$'

Working mapfile in: https://gist.github.com/LarsSchy/4aa75fd2a6bc7eb01a7cff9beb64b59a

**Comment by geographika** [comment]
Looks like it is a valid keyword, so I'll add to the schema, but I'm not sure if it has an effect. See comment at https://github.com/MapServer/MapServer-documentation/issues/677
