### ISSUE TITLE
Draw map without saving mapfile to disc

### ISSUE THREAD

**Issue by robrichter** [geographika/mappyfile#148]
Is there a way to draw map without creating mapfile on disc?

**Comment by geographika** [comment]
There is no way with the `mapserv` CGI application, but you can load a Mapfile with MapScript using `mapscript.msLoadMapFromString` (at least with the Python MapScript bindings).

**Comment by robrichter** [comment]
Thanks a lot! I was afraid of that. I hoped for removing Mapscript completely.
