### ISSUE TITLE
PATTERN elements with an odd number of values fail too quietly

### ISSUE THREAD

**Issue by ianturton** [geographika/mappyfile#16]
If you have a PATTERN element in your mapfile like:

    PATTERN 6 4 2 4 6 END

mappyfile throws a syntax error for an unrelated line number, this makes debugging very hard. Unfortunately MapServer and shp2img both eat the line silently (and I guess drop the last number) so are also no help in debugging.

A better error message or if the syntax error at least gave the right line it would help.

**Comment by geographika** [comment]
I've added a test for this and getting the line after the failure (an ``END`` is expected not a single number). Would you be able to provide a sample Mapfile to demonstrate this?

An alternative I'm considering for the project is a linter/validator - this could then load the points at the parsing stage but throw a validation warning when checked.

**Comment by geographika** [comment]
@ianturton the following snippet correctly shows the line with the error in the latest version of mappyfile (0.4.1):

```
MAP
    CLASS
        NAME "Test"
        STYLE
            PATTERN 6 4 2 4 5 END
        END
    END
END
```

```
Unexpected token Token(_END, u'END') at line 5, column 30.
Expected: set([u'SIGNED_INT', u'SIGNED_FLOAT'])
Context: <no context>
```
If this is not the case when testing as part of a larger Mapfile at http://mappyfile.geographika.net/ please reopen with any samples you can provide.
