### ISSUE TITLE
QUERYMAP parsing fails on STYLE line

### ISSUE THREAD

**Issue by ianturton** [geographika/mappyfile#17]
Given a mapfile containing:

 ```
QUERYMAP
    COLOR 255 255 0
    SIZE -1 -1
    STATUS OFF
    STYLE HILITE
  END
```
Parsing fails at the STYLE line (while reporting an unrelated line number). This appears to be a correct formulation according to the MapServer [manual](http://mapserver.org/mapfile/querymap.html). 

It looks like a grammar error but I don't want to mess with that ;-)

**Comment by geographika** [comment]
Thanks for reporting this. The grammar expects the ``STYLE`` to be a block with an ``END`` - but the keyword here is used differently. I'll see what the options are.

**Comment by sethgirvin** [comment]
@ianturton I've added a test (for master), which passes with a basic ``QUERYMAP`` example. Are you able to recreate with the master code branch?

**Comment by geographika** [comment]
@ianturton I've added a test (for master), which passes with a basic QUERYMAP example. Are you able to recreate with the master code branch?

**Comment by geographika** [comment]
@ianturton - the snippet above passes with the latest version (0.4.1), and can be tested online at http://mappyfile.geographika.net/ 
Please reopen if this fails in the context of a larger Mapfile.
