### ISSUE TITLE
Missing AUTO when parsing LABEL

### ISSUE THREAD

**Issue by geographika** [geographika/mappyfile#2]
Parsing the following:
```
    LABEL
      COLOR  0 0 0
      FONT Vera
      TYPE truetype
      SIZE 8
      POSITION AUTO
      PARTIALS FALSE
      OUTLINECOLOR 255 255 255			
    END 
```
doesn't output AUTO - the AUTO is dropped. 

AST looks as follows:

`[Tree(attr_name, [Token(NAME, 'POSITION')]), Tree(bare_string, [])])`

Likely due to following in grammar file:

`bare_string: NAME | "SYMBOL"i | "AUTO"i | "GRID"i | "CLASS"i`

**Comment by erezsh** [comment]
Ah, yes, in Lark tokens are always dropped by default, even if they are the only values.
To solve this, you could add a '!' to the rule name:
!bare_string: NAME | "SYMBOL"i | "AUTO"i | "GRID"i | "CLASS"i

**Comment by geographika** [comment]
Thanks @erezsh - `!bare_string` fixed these issues.
