### ISSUE TITLE
Missing end

### ISSUE THREAD

**Issue by zsiki** [geographika/mappyfile#24]
I've tested this nice project. I commented out an "END" at the middle of a map file and got  "recursion depth" error, the trace log is very long, last few lines (the same messages are repeated):
  File "/usr/lib/python2.7/functools.py", line 87, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/earley.py", line 257, in _compare_drv
    c = _compare_drv(t1, t2)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/earley.py", line 247, in _compare_drv
    _resolve_ambig(tree1)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/earley.py", line 267, in _resolve_ambig
    best = min(tree.children, key=cmp_to_key(_compare_drv))
  File "/usr/lib/python2.7/functools.py", line 87, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/earley.py", line 257, in _compare_drv
    c = _compare_drv(t1, t2)
  File "/usr/local/lib/python2.7/dist-packages/lark/parsers/earley.py", line 234, in _compare_drv
    if not (isinstance(tree1, Tree) and isinstance(tree2, Tree)):
RuntimeError: maximum recursion depth exceeded while calling a Python object

I attach the file (see the commented line at 3000) (renamed to txt because of the github limitation)
[x201703.txt](https://github.com/geographika/mappyfile/files/1166468/x201703.txt)

**Comment by zsiki** [comment]
It would be nice to get a message: missing block end at line ...

**Comment by aimdev** [comment]
diff x201703.txt x201703.map
66c66
< 	STATUS TRUE
---
> 	STATUS ON
3000c3000
< 	#END
---
> 	END ## unmatched end line 3000 METADATA	"DESCRIPTION"	"Egyebek"
3432c3432
< 			BACKGROUNDCOLOR 255 255 255
---
> 			# removed in V6 BACKGROUNDCOLOR 255 255 255
~/mapgen/test_maps$ mappyfile validate --version=7.6 x201703.map 
x201703.map validated successfully
1 file(s) validated (1 successfully)

**Comment by aimdev** [comment]
diff x201703.txt x201703.map
66c66
< 	STATUS TRUE
---
> 	STATUS ON
3000c3000
< 	#END
---
> 	END ## unmatched end line 3000 METADATA	"DESCRIPTION"	"Egyebek"
3432c3432
< 			BACKGROUNDCOLOR 255 255 255
---
> 			# removed in V6 BACKGROUNDCOLOR 255 255 255

mappyfile validate --version=7.6 x201703.map 
x201703.map validated successfully
1 file(s) validated (1 successfully)

**Comment by aimdev** [comment]
See attached
[differ.dif.txt](https://github.com/geographika/mappyfile/files/7966301/differ.dif.txt)

**Comment by geographika** [comment]
@zsiki - testing this again on the latest versions of mappyfile gives a slightly better error message. I don't think the parser will ever be able to poinpoint the location of this missing `END` in the middle, but hopefully this error is slightly less cryptic. Closing this issue now, and thanks for using mappyfile!

```
Unexpected token Token('$END', '') at line 5174, column 1.
Expected one of: 
	* VALUES
	* VALIDATION
	* GRID
	* QUERYMAP
	* OUTPUTFORMAT
	* CONFIG
	* MAP
	* LEGEND
	* ...
```
