### ISSUE TITLE
Use flake8 to lint the project?

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#29]
Usually I find it useful to flake8 linter to keep a clean code and nice code convention accross the project.
Do you think you'd like to have that in your project?

Doc:
http://flake8.pycqa.org/en/latest/

If you agree, I could make a PR for that.

You don't need to enforce all the rules, and you may want to keep our own style in some part of the code, but this can be tuned on demand.

**Comment by geographika** [comment]
@loicgasser - this would be very useful, so please create a pull request whenever you get a chance. I presume this would be run as part of travis? I had been using prospector locally, but intermittently.

**Comment by loicgasser** [comment]
yes it can be integrated with travis.
I'll add a code coverage report as well, so that we can spot the weak parts.
Will do it soon.
