### ISSUE TITLE
Unsupported arithmetic operation for `=` in EXPRESSION

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#34]
```python
import mappyfile
mappyfile.loads('EXPRESSION ([typ_nr] = 1)')
```
this expression above will fail.

http://mapserver.org/mapfile/expressions.html#arithmetic-expressions-that-return-a-logical-value

**Comment by geographika** [comment]
The loads method will only work with a "composite" object(s). I'll need to document this better somewhere. The following should work:

```
CLASS
    EXPRESSION (( [typ_nr] = 1 ))
END
```

Or is this failing as part of a larger Mapfile?

**Comment by loicgasser** [comment]
yep sorry this does work, indeed makes sense to have a starting and ending tag.
