### ISSUE TITLE
Create a unique logger for mappyfile logger

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#36]
At the moment logging is imported directly in the different modules, making it impossible to shut him up.

The simple solution would be to create a logger named `mappyfile` and then import it everywhere.

With a simple note in a script:
```
logging.getLogger('mappyfile').setLevel(logging.WARNING)
```

you can set a custom logging level.

**Comment by geographika** [comment]
Good idea - added. Calling scripts can now use:

```
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('mappyfile').setLevel(logging.WARNING)
```

**Comment by loicgasser** [comment]
cool! Would you mind creating a new release with all the latest changes?

**Comment by geographika** [comment]
@loicgasser  - done.
