### ISSUE TITLE
Map file with "FILTER ( type LIKE '611_%' )" can't be parse.

### ISSUE THREAD

**Issue by BarreSebastien** [geographika/mappyfile#37]
Hello,

I've got  a Mapfile whith the line "FILTER ( type LIKE '611_%' )" in it and when I try do parse the file I've got this error message : 
ERROR:root:Unexpected token Token(NAME, u'LIKE') at line 8283, column 18.
Expected: set([u'__AND13', u'__NE22', u'__IN21', '__TILDE', '__PLUS', '__EQUAL', '__LESSTHAN', '__MORETHAN', '__RPAR', '__ANONSTR_19', '__ANONSTR_18', '__LPAR', '__ANONSTR_20', u'__OR11', '__ANONSTR_12', u'__EQ23', '__ANONSTR_17', '__ANONSTR_16', '__ANONSTR_15', '__ANONSTR_14'])
Context: <no context>
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\mappyfile\parser.py", line 99, in parse
    ast = self.earley.parse(text)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\lark.py", line 193, in parse
    return self.parser.parse(text)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parser_frontends.py", line 115, in parse
    return self.parser.parse(tokens)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parsers\earley.py", line 209, in parse
    column = scan(i, token, column)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parsers\earley.py", line 198, in scan
    raise UnexpectedToken(token, expect, stream, i)
UnexpectedToken: Unexpected token Token(NAME, u'LIKE') at line 8283, column 18.
Expected: set([u'__AND13', u'__NE22', u'__IN21', '__TILDE', '__PLUS', '__EQUAL', '__LESSTHAN', '__MORETHAN', '__RPAR', '__ANONSTR_19', '__ANONSTR_18', '__LPAR', '__ANONSTR_20', u'__OR11', '__ANONSTR_12', u'__EQ23', '__ANONSTR_17', '__ANONSTR_16', '__ANONSTR_15', '__ANONSTR_14'])
Context: <no context>
ERROR:root:Parsing with LALR and Earley unsuccessful
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\mappyfile\utils.py", line 9, in load
    ast = p.parse_file(fn)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\mappyfile\parser.py", line 76, in parse_file
    return self.parse(text, fn=fn)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\mappyfile\parser.py", line 99, in parse
    ast = self.earley.parse(text)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\lark.py", line 193, in parse
    return self.parser.parse(text)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parser_frontends.py", line 115, in parse
    return self.parser.parse(tokens)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parsers\earley.py", line 209, in parse
    column = scan(i, token, column)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\lark\parsers\earley.py", line 198, in scan
    raise UnexpectedToken(token, expect, stream, i)
lark.common.UnexpectedToken: Unexpected token Token(NAME, u'LIKE') at line 8283, column 18.
Expected: set([u'__AND13', u'__NE22', u'__IN21', '__TILDE', '__PLUS', '__EQUAL', '__LESSTHAN', '__MORETHAN', '__RPAR', '__ANONSTR_19', '__ANONSTR_18', '__LPAR', '__ANONSTR_20', u'__OR11', '__ANONSTR_12', u'__EQ23', '__ANONSTR_17', '__ANONSTR_16', '__ANONSTR_15', '__ANONSTR_14'])
Context: <no context>

Thank you for your work.
Sébastien Barre.

**Comment by geographika** [comment]
@BarreSebastien - what data are you filtering with that expression? `LIKE` isn't one of the comparisons listed at http://mapserver.org/mapfile/expressions.html

If you are filtering in a database you should now use the following syntax as recommended at http://mapserver.org/mapfile/layer.html 

``PROCESSING 'NATIVE_FILTER=id=234'``

These filters should be wrapped in quotes.

**Comment by BarreSebastien** [comment]
Thank-you for your response,

My Mapfiles are generated by a script (witch I can’t change), so I try to use your mappyfile to make changes on it “a posteriori”.

Sorry I haven’t seen that this FILTER where not on the right form (I will be more attentive the next time).

Thank you for your help.

Cordially,


Sébastien Barre

Chargé de projet SIG
CDA de La Rochelle

16 rue Jacques de Vaucanson
Zone industrielle
17180 Périgny



Tél : 05 46 30 34 22

Fax : 05 46 30 34 29






De : Seth G [mailto:notifications@github.com]
Envoyé : lundi 28 août 2017 00:25
À : geographika/mappyfile <mappyfile@noreply.github.com>
Cc : BARRE Sébastien <sebastien.barre@agglo-larochelle.fr>; Mention <mention@noreply.github.com>
Objet : Re: [geographika/mappyfile] Map file with "FILTER ( type LIKE '611_%' )" can't be parse. (#37)


@BarreSebastien<https://github.com/barresebastien> - what data are you filtering with that expression? LIKE isn't one of the comparisons listed at http://mapserver.org/mapfile/expressions.html

If you are filtering in a database you should now use the following syntax as recommended at http://mapserver.org/mapfile/layer.html

PROCESSING 'NATIVE_FILTER=id=234'

These filters should be wrapped in quotes.

**Comment by geographika** [comment]
@BarreSebastien - no problem. Let me know if any parts of the Mapfile don't parse in mappyfile but work with MapServer.

**Comment by BarreSebastien** [comment]
Hi,

In that case, for information, the
FILTER (type LIKE ‘xxx%’)
command is perfectly operational on a MapServer 6.4 while
PROCESSING "NATIVE_FILTER=type LIKE '523_%'"
doesn’t work.


Sébastien Barre

**Comment by archaeogeek** [comment]
Hi,

I've also come across this, and can confirm that LIKE filters work just fine in mapserver 6.4 but cause mappyfile to fail.

Thanks

Jo
