### ISSUE TITLE
Unable to parse list expression when value starts with a number

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#38]
```python
import mappyfile

c="""
CLASS
  EXPRESSION {2_Klass,Rte2etr}
  STYLE
    ANGLE 360
    COLOR 255 255 26
    OPACITY 100
    WIDTH 1
  END
END
"""
mappyfile.loads(c)
```
This will raise:

```
lark.common.UnexpectedToken: Unexpected token Token(NAME, '_Klass') at line 3, column 15.
Expected: set(['__COMMA', '__RBRACE'])
Context: <no context>
````

The same without the `2` works fine.

**Comment by geographika** [comment]
Reproduced and test added at https://github.com/geographika/mappyfile/blob/master/tests/test_expressions.py#L210

Hopefully it can be fixed for the LALR parser.

**Comment by geographika** [comment]
In a related issue numbers in unquoted filenames also fail to parse: 

```
    WEB
        IMAGEURL "/tmp/"
        TEMPLATE example3.html
    END
```

See test in test_snippets.py - `test_filename`

**Comment by geographika** [comment]
Transformer and pprinting fixed. All tests now passing in master.
