### ISSUE TITLE
Expression and/or operator keeps failing, parenthesis 

### ISSUE THREAD

**Issue by loicgasser** [geographika/mappyfile#41]
```python
import mappyfile

c="""
CLASS
  NAME "Autobahn"
  EXPRESSION ( '[construct]' eq 'keine' ) or ( '[contruct]' eq 'twice' )
  STYLE
    ANGLE 360
    COLOR 0 0 0
    OPACITY 100
    WIDTH 6
  END
END
"""
mappyfile.loads(c)
```
I found another error with expressions. 

```
Expected: set([u'__LABEL34', u'__CONFIG30', u'__LAYER35', u'__REFERENCE41', u'__LEADER36', u'__COMPOSITE29', u'PATH', u'__METADATA4', u'__POINTS0', '__LBRACE', u'__CLUSTER28', u'__CLASS8', u'__SCALEBAR42', u'__JOIN33', u'__VALIDATION5', u'SIGNED_INT', u'__NOT10', u'SIGNED_FLOAT', u'__STYLE44', u'__FEATURE9', u'STRING2', u'STRING3', u'__PATTERN1', u'__FONTSET31', u'__SCALETOKEN43', u'__INCLUDE32', u'__WEB45', u'AUTO', u'__PROJECTION2', u'__GRID7', u'__OUTPUTFORMAT39', u'_END', '__LPAR', u'__MAP38', u'__LEGEND37', u'NAME', '__LSQB', u'REGEXP2', u'__QUERYMAP40', u'REGEXP1', u'__SYMBOL6', u'RUNTIME_VAR', u'__VALUES3', '__BANG', u'STRING1'])
Context: <no context>
```

changing the prathesis to ` ( '[construct]' eq 'keine'  or  '[contruct]' eq 'twice' )` solves the issue.

It think there is still some work to be done with expressions in general.

 `(( '[construct]' eq 'keine') or ( '[contruct]' eq 'twice' ))` also does

**Comment by geographika** [comment]
Is the expression definitely valid in MapServer?
All the examples at http://mapserver.org/mapfile/expressions.html#logical-expressions seem to wrap the whole statement in brackets e.g. 

` ( '[construct]' eq 'keine'  or '[contruct]' eq 'twice' )`

The expressions are probably the trickiest part of the parser. I may see if there is a way to move some of the logic to the transformer and accept anything between brackets. 
In fact I think there are even bugs in the MapServer expression parsing..does this run for you in MapServer?

`(( '[construct]' eq 'keine') or ( '[contruct]' eq 'twice' )) # a comment and a stray bracket )`

**Comment by loicgasser** [comment]
You give me doubts, let me double check on Monday. Thank you for your support.

**Comment by geographika** [comment]
@loicgasser - I did some brief testing with regards to these expressions. Whilst no outer brackets don't seem to make MapServer throw an error when loading the Mapfile, no features were displayed at all. 

I think that this is an invalid expression and so the parser exception is valid. 

Test Mapfile below. 

```
MAP
    NAME "Test"
    EXTENT -10 -10 10 10
    SIZE 400 400

    LAYER
        NAME "TestLayer"
        STATUS ON
        TYPE POINT
        PROCESSING "ITEMS=field1,field2"
        FEATURE
            POINTS 0 0 END
            ITEMS "2;3"            
        END
        FEATURE
            POINTS 5 5 END
            ITEMS "4;6"            
        END
        CLASS
            TEXT (([field1] ^ [field2] + 2) * 2)
            # following works with one feature shown
            #EXPRESSION (( [field1] eq 2 ) or ( [field1] eq 99 ))
            # with the following expression no features are shown
            EXPRESSION ( [field1] eq 2 ) or ( [field1] eq 99 )
            LABEL
              COLOR  150 150 150
            END
        END
    END
END
```

**Comment by loicgasser** [comment]
Yes I think you are right.
