### ISSUE TITLE
Multiple INCLUDE and expand_includes=False

### ISSUE THREAD

**Issue by peterschaer** [geographika/mappyfile#43]
I have a mapfile with multiple INCLUDE statements:

```python
import mappyfile

c="""
MAP
    NAME "test_map"
    STATUS ON
    EXTENT 2550300 1120800 2688900 1247400
    UNITS METERS
    PROJECTION
        "init=epsg:2056"
    END
	LAYER
		INCLUDE "a.map"
		INCLUDE "b.map"
        NAME "test_layer"
	END
END
"""
mf = mappyfile.loads(c,expand_includes=False)
print mappyfile.dumps(mf)`
```
which dumps as

```
MAP
    NAME "test_map"
    STATUS ON
    EXTENT 2550300 1120800 2688900 1247400
    UNITS METERS
    PROJECTION
        "init=epsg:2056"
    END
    LAYER
        INCLUDE "b.map"
        NAME "test_layer"
    END
END
```
Only the second INCLUDE is dumped. Any idea why?

**Comment by loicgasser** [comment]
hello, I can't reproduce.
What version mappyfile are you using?

**Comment by peterschaer** [comment]
I'm using mappyfile 0.4.3 on python 2.7.5

**Comment by loicgasser** [comment]
same here Python 2.7.12 running on Ubuntu.
very weird looking at the code I don't see how it's possible though.

Starting here:
https://github.com/geographika/mappyfile/blob/master/mappyfile/utils.py#L16

Set here:
https://github.com/geographika/mappyfile/blob/master/mappyfile/parser.py#L13

The recursively loads includes within the parser instance.
https://github.com/geographika/mappyfile/blob/master/mappyfile/parser.py#L80

**Comment by geographika** [comment]
@peterschaer - this has been fixed in master with the commit https://github.com/geographika/mappyfile/commit/62f5103c0afc01abc7158e9a16e5d135249db8a6
I'll be putting together a new release in the next few days.

**Comment by peterschaer** [comment]
Great! Thanks very much!
