### ISSUE TITLE
Lark version not fixed

### ISSUE THREAD

**Issue by vvmruder** [geographika/mappyfile#45]
In the packages setup.py file the "lark-parser" version is not fixed to a number. So if we use it now pip installs the newest version of "lark-parser" which is 0.5.1

This has a problem with this call:
https://github.com/geographika/mappyfile/blob/master/mappyfile/parser.py#L28

It seems that "lark-parser" does not support parameter "earley__all_derivations" any longer in newest version. So parsing has been corrupted in this combination.

If I install manually version 0.4.1 of "lark-parser" everything works like expected:
```pip install "lark-parser==0.4.1"```

Suggestion is to set version of lark-parser fix to 0.4.1 in setup.py

**Comment by erezsh** [comment]
Author of Lark here, any version that is 0.4.x will work.
The parameter `earley__all_derivations` is there just for speed optimization. In 0.5.1, it's no longer necessary and can be removed.

**Comment by geographika** [comment]
@vvmruder - thanks for noting this. 
setup.py now contains the following dependency ranges:

`lark-parser>=0.5, <0.6', 'jsonschema >=2.0, <3.0`

The ``earley__all_derivations`` keyword was also removed with the latest v0.6.0 release. 
With new releases of mappyfile I'll test with newer versions of the above and update accordingly.
