### ISSUE TITLE
AttributeError: module 'mappyfile' has no attribute 'loads'

### ISSUE THREAD

**Issue by janpisl** [geographika/mappyfile#62]
When trying to run this [example](https://mappyfile.readthedocs.io/en/latest/api/main.html#mappyfile.loads) from the mappyfile docs:

```
import mappyfile
s = '''MAP NAME "TEST" END'''

d = mappyfile.loads(s)
fn = r"C:\Data\mymap.map"
mappyfile.save(d, fn)
```

I get the following error:

`AttributeError: module 'mappyfile' has no attribute 'loads'`

I get the same error when trying any other command (open, load, etc.) . I am using Ubuntu 16.04 and Python 3.5. Is it something I am doing wrong?

**Comment by geographika** [comment]
Are you using a current version?
Could you try:

```
import mappyfile
print(mappyfile.__version__)
```
The API was redesigned in v0.7+

**Comment by janpisl** [comment]
Thanks for the reply. When I try what you suggest, I get:

`AttributeError: module 'mappyfile' has no attribute '__version__'
`



If I print the module's attributes like this:

`print(dir(mappyfile))
`

I get:

`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'mappyfile']`


Perhaps there is something really simple that I am missing?

**Comment by geographika** [comment]
You haven't by chance named your test script mappyfile.py ?

**Comment by janpisl** [comment]
Oh yeah that was it. Thanks a lot.
