### ISSUE TITLE
DefaultOrderedDict save it to a file with pickle

### ISSUE THREAD

**Issue by guardeivid** [geographika/mappyfile#68]
Hi, 
Excellent work.
I am trying to save the dictionary open with mappyfile in a file, using **`pickle`**, but I get the following error:
```py
mapy = mappyfile.open(path)
pickle.dump(mapy, open('file', 'wb'))
```

```sh
_pickle.PicklingError: fifth element of the tuple returned by __reduce__ must be an iterator, not odict_items.
```
I understand that this is the function::
```py
    def __reduce__(self):
        if self.default_factory is None:
            args = tuple()
        else:
            args = self.default_factory,
        return type(self), args, None, None, self.items()
```

Is it possible to return an **`iterator`** instead of **`self.items()`**?

Thanks!

**Comment by geographika** [comment]
@guardeivid - glad you like the library. 
I added a pickle test but wasn't able to recreate the issue. Would you be able to provide a minimal Mapfile snippet that causes this?

**Comment by geographika** [comment]
Ok the pickle test works in Python2 and not Python3, I'll add a fix for this. Thanks for reporting.

**Comment by guardeivid** [comment]
Yes, the error was in Python3. Great now it works correctly, 

Many Thanks!
