### ISSUE TITLE
Optional comment on end tags

### ISSUE THREAD

**Issue by arbakker** [geographika/mappyfile#69]
First of all, thanks for creating this cool project! 

Feature request: to increase readability of mapfiles I use the convention to add comments on END tags to indicate what object the END tag is closing.  Is this something that you are willing to add to mappyfile? 
The END tag comment could be only applied to specific objects, or made dependent on the length of the content of the object (bigger than 20 lines), to avoid cluttering the mapfile too much.

**Comment by geographika** [comment]
@arbakker - sounds very feasible with some modifications to pprint.py
I'll add it to the road map.

**Comment by geographika** [comment]
Added to the latest release - see [http://mappyfile.geographika.net/](http://mappyfile.geographika.net/) > Settings >  Add Closing Block Comments for an online example
