### ISSUE TITLE
Problem with NOT in filters

### ISSUE THREAD

**Issue by ianturton** [geographika/mappyfile#77]
Given a snippet like:

LAYER
         TYPE POINT
         NAME 'filters_test003'
         FILTER (not("roadno" like 'C%') and not("roadno" like 'A%') and not("roadno" like 'B%') and (street_class = 8))
END
Throws this error:

E               UnexpectedCharacters: No terminal defined for '=' at line 5 col 115
E               
E               t("roadno" like 'B%') and (street_class = 8))
E                                                       ^

local/lib/python2.7/site-packages/lark/lexer.py:167: UnexpectedCharacters

From my reading of the grammar this should be legal (and our existing mapfile works fine)

**Comment by geographika** [comment]
@ianturton - shouldn't street_class be in square brackets?
Does `and ([street_class] = 8))` parse?

**Comment by ianturton** [comment]
it does as in fact does "street_class" = 8 - is quoting or bracketing attributes required?

**Comment by geographika** [comment]
As far as I was aware it should do - https://mapserver.org/mapfile/expressions.html#using-attributes
If you load the Mapfile and then dump it out using MapScript what does the expression look like?

**Comment by geographika** [comment]
@ianturton - hopefully the ``NOT`` issue is fixed with #100 (see also #85)
