### ISSUE TITLE
Parser fails if you pass in a io.StringIO object instead of a file like object 

### ISSUE THREAD

**Issue by ianturton** [geographika/mappyfile#94]
Line 165 in parser.py 

'''
if os.path.isfile(fp.name):
            fn = fp.name  # name is a read-only attribute and may not be present on all file-like objects.
        else:
            fn = None
        return self.parse(text, fn)
''' 

Fails if fp is an io.StringIO object as it has no attribute name, 

Seems that `if hasattr(fp, 'name'):` is a better test.

**Comment by geographika** [comment]
Fixed with #95. Thanks @ianturton
